version: '3.9'
services:
  db_todos:
    restart: always
    container_name: db_todos
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: admin
    image: postgres:15.2-alpine